### ISSUE TITLE
ERROR - 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by el3ctro4ndre** [ChemistryGull/SomeDL#27]
Hi, I report an error with the metadata fetching of this song: [Dj Valium](https://music.youtube.com/watch?v=XwysdYPVLMo&si=i77X2y7g7ExSmGQP).
It persisted even after retrying.

<img width="1222" height="520" alt="Image" src="https://github.com/user-attachments/assets/ce56b523-cd2d-41a7-b57a-01120aaaad49" />

**Comment by ChemistryGull** [comment]
Thanks a lot for notifying! I have spotted the issue (an uncaught `None` value from yt lyrics). I've fixed it, it should work with version 1.3.2 (out very soon).

**Comment by el3ctro4ndre** [comment]
Thank your for all the good work you are doing!

**Comment by ChemistryGull** [comment]
Thanks! Fix now out with version 1.3.3 (1.3.2 had some minor issues).
